GET http://localhost:8000/api/users
Content-Type: application/json
Accept: application/json

###

POST http://localhost:8000/api/users
Content-Type: application/json

{
    "name": "buyer1",
    "surname": "buyer1",
    "email": "buyer1@gmail.com",
    "password": "12345678",
    "role": "buyer"
}

###

POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "seller1@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:8000/api/seller/orders/new
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

###
GET http://localhost:8000/api/seller/orders/pending
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

### 
GET http://localhost:8000/api/seller/orders/adjusted
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

### 
GET http://localhost:8000/api/seller/orders/ready
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

### 
GET http://localhost:8000/api/seller/orders/history
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

### 
GET http://localhost:8000/api/seller/orders/2
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

###
PUT http://localhost:8000/api/seller/orders/1/mark-pending
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

### Actualizar el peso y precio del pedido 1
PUT http://localhost:8000/api/seller/orders/1/update
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

{
"lines": [
    {
      "id": 1, 
      "real_weight": 22.10
    },
    {
      "id": 2,
      "quantity": 2,
      "real_weight": 3.4
    }
  ]
}

### Actualizar el peso y precio del pedido 1 pero sobrepasando el stock (funciona)
PUT http://localhost:8000/api/seller/orders/1/update
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

{
"lines": [
    {
      "id": 1, 
      "real_weight": 30
    },
    {
      "id": 2,
      "quantity": 100,
      "real_weight": 100
    }
  ]
}

### 
PUT http://localhost:8000/api/seller/orders/1/mark-ready
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

###
PUT http://localhost:8000/api/seller/orders/1/mark-completed
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

###
PUT http://localhost:8000/api/seller/orders/2/cancel-reject
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

{
    "rejection_reason": "El cliente ha tenido un imprevisto y no podrá seguir con la solicitud del pedido"
}

###
GET http://localhost:8000/api/seller/pickup-points
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

###
POST http://localhost:8000/api/seller/pickup-points/store
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

{
  "seller_id": 1, 
  "address": "La Vital",
  "city": "Gandia",
  "postal_code": "46701"
}

###
PUT http://localhost:8000/api/seller/pickup-points/update/1
Authorization: Bearer 15|TIUeLXZVsP2B0KTbkWUUb6W5Hhti6Z6ydRoega6A21db38af
Content-Type: application/json
Accept: application/json

{
  "seller_id": 1, 
  "address": "IES Jaume II el Just",
  "city": "Tavernes de la Valldigna",
  "postal_code": "46760"
}