name: Build and deploy PHP app to Azure Web App - ProxiMarktDAW

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      # Instalamos dependencias entrando directamente en backend
      - name: Install dependencies
        run: |
          cd backend
          if [ -f "composer.json" ]; then
            composer install --prefer-dist --no-progress --no-dev --optimize-autoloader
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C17D54B6E9CD49338D901EBCAFC01B9C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CD8F87D5AA46408DAC0C742D1FBC90D0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74C184AC5100443DB060B77E81FAF032 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ProxiMarktDAW'
          package: .
