# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - proximarkt-proyecto

on:
  push:
    branches:
      - pruebaMain
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'backend/composer.json' # <-- MAGIA 1: Buscamos en la carpeta correcta

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        working-directory: ./backend # <-- MAGIA 2: Instalamos las librerías de Laravel ahí dentro
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: . # <-- Subimos todo manteniendo la estructura para que Nginx no se pierda

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # Estas son tus contraseñas NUEVAS generadas por Azure. ¡Intactas!
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C8B9D91C4BB2411AAEBFDDD95B2ED092 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C5747836B4984EB2A5444EFA55F731C5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EC39AF24B7124DC7B672787CBC3FA7AB }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'proximarkt-proyecto'
          slot-name: 'Production'
          package: .
